# Generated by Django 3.1.2 on 2020-11-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eventtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventorganizer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=200)),
                ('eventdescription', models.CharField(max_length=300)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('eventlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventlocation')),
                ('eventorganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.organizer')),
                ('eventtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
        ),
    ]
