# Generated by Django 3.1.2 on 2020-11-15 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endtime',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='starttime',
            new_name='startTime',
        ),
        migrations.AddField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='event',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdescription',
            field=models.CharField(max_length=300, null=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventlocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventlocation', verbose_name='Event Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventname',
            field=models.CharField(max_length=200, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventorganizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.organizer', verbose_name='Event Orgainzer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype', verbose_name='Event Type'),
        ),
    ]
