# Generated by Django 3.1.2 on 2020-11-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='createdBy',
        ),
    ]
