# Generated by Django 3.1.2 on 2020-11-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='createdTime',
        ),
    ]
