# Generated by Django 3.1.2 on 2020-11-17 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201117_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
