# Generated by Django 3.1.2 on 2020-11-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
